2024-12-09 16:10:08 - INFO - rabbitmq_client.client: Closing RabbitMQ connection...
2024-12-09 16:10:08 - ERROR - pika.channel: Unexpected frame: <METHOD(['channel_number=1', 'frame_type=1', "method=<Basic.CancelOk(['consumer_tag=ctag1.8c193892a2b04b2c8e23896b096eb9a2'])>"])>
2024-12-09 16:10:08 - INFO - pika.channel: Closing channel (0): 'Normal shutdown' on <Channel number=1 OPEN conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10c50f4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-12-09 16:10:08 - INFO - pika.channel: Received <Channel.CloseOk> on <Channel number=1 CLOSING conn=<SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x10c50f4d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>>
2024-12-09 16:10:08 - INFO - pika.adapters.blocking_connection: Closing connection (200): Normal shutdown
2024-12-09 16:10:08 - INFO - pika.connection: Closing connection (200): 'Normal shutdown'
2024-12-09 16:10:08 - ERROR - pika.adapters.utils.io_services_utils: _AsyncBaseTransport._produce() failed, aborting connection: error=IndexError('pop from an empty deque'); sock=<socket.socket fd=14, family=30, type=1, proto=6, laddr=('::1', 60330, 0, 0), raddr=('::1', 5672, 0, 0)>; Caller's stack:
Traceback (most recent call last):
  File "/Users/akaostashevskaya/miniconda3/envs/pyqt_venv/lib/python3.13/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
    ~~~~~~~~~~~~~^^
  File "/Users/akaostashevskaya/miniconda3/envs/pyqt_venv/lib/python3.13/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
Traceback (most recent call last):
  File "/Users/akaostashevskaya/miniconda3/envs/pyqt_venv/lib/python3.13/site-packages/pika/adapters/utils/io_services_utils.py", line 1103, in _on_socket_writable
    self._produce()
    ~~~~~~~~~~~~~^^
  File "/Users/akaostashevskaya/miniconda3/envs/pyqt_venv/lib/python3.13/site-packages/pika/adapters/utils/io_services_utils.py", line 822, in _produce
    chunk = self._tx_buffers.popleft()
IndexError: pop from an empty deque
2024-12-09 16:10:08 - INFO - pika.adapters.utils.io_services_utils: _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=IndexError('pop from an empty deque'); <socket.socket fd=14, family=30, type=1, proto=6, laddr=('::1', 60330, 0, 0), raddr=('::1', 5672, 0, 0)>
2024-12-09 16:10:08 - INFO - pika.adapters.utils.io_services_utils: Deactivating transport: state=1; <socket.socket fd=14, family=30, type=1, proto=6, laddr=('::1', 60330, 0, 0), raddr=('::1', 5672, 0, 0)>
2024-12-09 16:10:08 - ERROR - pika.adapters.base_connection: connection_lost: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-12-09 16:10:08 - INFO - pika.connection: AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",); pending-error=ConnectionClosedByClient: (200) 'Normal shutdown'
2024-12-09 16:10:08 - INFO - pika.connection: Stack terminated due to StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-12-09 16:10:08 - INFO - pika.adapters.utils.io_services_utils: Closing transport socket and unlinking: state=2; <socket.socket fd=14, family=30, type=1, proto=6, laddr=('::1', 60330, 0, 0), raddr=('::1', 5672, 0, 0)>
2024-12-09 16:10:08 - ERROR - pika.adapters.blocking_connection: Unexpected connection close detected: StreamLostError: ("Stream connection lost: IndexError('pop from an empty deque')",)
2024-12-09 16:10:08 - ERROR - rabbitmq_client.client: Error while stopping client: [Errno 9] Bad file descriptor
2024-12-09 16:10:08 - ERROR - rabbitmq_client.client: Stream connection lost: IndexError('pop from an empty deque')
2024-12-09 16:10:08 - INFO - rabbitmq_client.client: Client stopped successfully.
